---
- name: install tomcat10 app
  hosts: all
  tasks:
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat10-admin 
      apt:
        name: tomcat10-admin
        state: present
    - name: copy custamised tomcatusers.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change port of tomcat 8080 to 9090
      replace: 
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: pause for 1 min
      pause:
        minutes: 1
    - name: check tomcat responce on server1
      uri:
        url: "http://172.31.44.123:9090"
        status_code: 200
    - name: check tomcat responce on server2
      uri:
        url: "http://172.31.34.155:9090"
        status_code: 200
...          
