---
- name: uninstall apps on remote servers 
  hosts: all
  tasks:
    - name:
      apt:
        name: tomcat10
        state: absent
        update_cache: yes
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
    - name: install tomcat10-admin      
      apt:
        name: tomcat10-admin
        state: present
...          
